-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(p.PRICE * off.SALES_AMOUNT) AS SALES
FROM PRODUCT AS p JOIN OFFLINE_SALE AS off ON p.PRODUCT_ID = off.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE