-- 코드를 작성해주세요
SELECT COUNT(info.FISH_TYPE) AS FISH_COUNT, name.FISH_NAME AS FISH_NAME
FROM FISH_INFO AS info JOIN FISH_NAME_INFO AS name ON info.FISH_TYPE = name.FISH_TYPE
GROUP BY name.FISH_NAME
ORDER BY FISH_COUNT DESC