SELECT SUM(g.SCORE) AS SCORE , e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_DEPARTMENT AS d
    INNER JOIN
        HR_EMPLOYEES AS e ON d.DEPT_ID = e.DEPT_ID
    INNER JOIN
        HR_GRADE AS g ON e.EMP_NO = g.EMP_NO
WHERE g.YEAR = '2022'
GROUP BY g.EMP_NO
ORDER BY SUM(g.SCORE) DESC
LIMIT 1